---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.7
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
    package_system: "python3.12"
  galaxy: requirements.yml
  python: requirements.txt
  #system: bindep.txt

images:
  base_image:
    name: quay.io/centos/centos:stream8

additional_build_files:
  - src: files/ansible.cfg
    dest: configs

additional_build_steps:
  prepend_base: |
    RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    yum update -y && \
    yum install glibc-all-langpacks langpacks-en -y && \
    yum upgrade -y && \
    yum install python3.12 python3.12-devel -y && \
    yum clean all && \
    rm -rf /var/cache/yum
