---
collections:
  - name: ansible.netcommon
    # version: 2.5.1
  - name: ansible.posix
  - name: ansible.scm
  - name: ansible.utils
  - name: arista.avd
  - name: arista.eos
  - name: cisco.ios
  - name: community.docker
  - name: community.general
  - name: community.mysql
  - name: community.postgresql
  - name: fortinet.fortianalyzer
  - name: fortinet.fortimanager
  - name: fortinet.fortios
  - name: infoblox.nios_modules
  - name: lvrfrc87.git_acp
  - name: napalm.napalm
  - name: netbox.netbox
  - name: paloaltonetworks.panos
roles:
  - name: batfish.base
